/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package securitysystem;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.Timer;

import java.sql.*;
import javax.swing.*;

/**
 *
 * @author jb999
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    // hardcoded username and password
    // private final String USERNAME = "admin";
    // private final String PASSWORD = "1234";
    private String selectedUsername = null; // username from Users screen
    
    private int attemptCount = 0;
   
    
    
 
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        btnLogin.addActionListener(new LoginAction());
        btnExit.addActionListener(e -> {
            // Go back to the Users page
            new Users().setVisible(true);
            dispose(); // close the login window
        });



        // Show/Hide password
        seePassword.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (seePassword.isSelected()) {
                    textPassword.setEchoChar((char) 0); // show text
                } else {
                    textPassword.setEchoChar('*'); // hide text
                }
            }
        });
    }

    // Constructor used when a username is passed from Users.java
    public Login(String username) {
        this();
        selectedUsername = username;
        textUser.setText(username);
        textUser.setEditable(false); // lock the username field
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        textUser = new javax.swing.JTextField();
        textPassword = new javax.swing.JPasswordField();
        seePassword = new javax.swing.JCheckBox();
        btnExit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        btnLogin.setBackground(new java.awt.Color(153, 153, 153));
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 70, 30));

        textUser.setBackground(new java.awt.Color(153, 153, 153));
        textUser.setForeground(new java.awt.Color(255, 255, 255));
        textUser.setBorder(null);
        textUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUserActionPerformed(evt);
            }
        });
        getContentPane().add(textUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 250, 30));

        textPassword.setBackground(new java.awt.Color(153, 153, 153));
        textPassword.setForeground(new java.awt.Color(255, 255, 255));
        textPassword.setBorder(null);
        getContentPane().add(textPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 250, 30));

        seePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seePasswordActionPerformed(evt);
            }
        });
        getContentPane().add(seePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        btnExit.setBackground(new java.awt.Color(153, 153, 153));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("<");
        btnExit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 30, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/securitysystem/martin-martz-W0NRebXbsjM-unsplash.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textUserActionPerformed

    private void seePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seePasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seePasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private class LoginAction implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            String user = textUser.getText().trim();
            String pass = new String(textPassword.getPassword());

            if (user.isEmpty() || pass.isEmpty()) {
                JOptionPane.showMessageDialog(Login.this, "Please fill in all fields.");
                return;
            }

            try (Connection conn = DBConnection.getConnection()) {
                if (conn == null) {
                    JOptionPane.showMessageDialog(Login.this, "Database connection failed!");
                    return;
                }

                String query = "SELECT * FROM users WHERE username = ? AND password = SHA2(?, 256)";
                PreparedStatement stmt = conn.prepareStatement(query);
                stmt.setString(1, user);
                stmt.setString(2, pass);
                ResultSet rs = stmt.executeQuery();

                if (rs.next()) {
                    // Update lastLogin time
                    PreparedStatement updateStmt = conn.prepareStatement(
                        "UPDATE users SET lastLogin = NOW() WHERE username = ?");
                    updateStmt.setString(1, user);
                    updateStmt.executeUpdate();

                    // Go directly to DesktopEnvironment (no message)
                    new DesktopEnvironment().setVisible(true);
                    dispose();
                } else {
                    attemptCount++;
                    JOptionPane.showMessageDialog(Login.this, "Incorrect username or password.");

                    if (attemptCount >= 5) {
                        btnLogin.setEnabled(false);
                        JOptionPane.showMessageDialog(Login.this,
                                "Too many attempts! Login disabled for 10 seconds.");
                        Timer timer = new Timer(10000, evt -> {
                            btnLogin.setEnabled(true);
                            attemptCount = 0;
                        });
                        timer.setRepeats(false);
                        timer.start();
                    }
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(Login.this, "Database error: " + ex.getMessage());
            }
        }
    }


    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JCheckBox seePassword;
    private javax.swing.JPasswordField textPassword;
    private javax.swing.JTextField textUser;
    // End of variables declaration//GEN-END:variables
}
