/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package securitysystem;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author jb999
 */
public class StartingScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StartingScreen.class.getName());

    /**
     * Creates new form StartingScreen
     */
    public StartingScreen() {
        initComponents();
        setLocationRelativeTo(null);
        showDateTime();
        
        // When clicked, go to Users window
        this.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                openUsersScreen();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTime = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTime.setBackground(new java.awt.Color(0, 0, 0));
        txtTime.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        txtTime.setText("-- --");
        txtTime.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 214, 235, -1));

        txtDate.setBackground(new java.awt.Color(0, 0, 0));
        txtDate.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        txtDate.setText("-- -- -- --");
        txtDate.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 251, 256, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/securitysystem/martin-martz-W0NRebXbsjM-unsplash.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
        private void showDateTime() {
        Timer timer = new Timer(1000, e -> {
            Date now = new Date();
            txtTime.setText(new SimpleDateFormat("hh:mm:ss a").format(now));
            txtDate.setText(new SimpleDateFormat("EEEE, MMMM dd").format(now));
        });
        timer.start();
    }

    private void openUsersScreen() {
        new Users().setVisible(true);
        dispose(); // close starting screen
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StartingScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txtDate;
    private javax.swing.JLabel txtTime;
    // End of variables declaration//GEN-END:variables
}
