/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package securitysystem;

import java.awt.event.*;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.*;
/**
 *
 * @author jb999
 */
public class Users extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Users.class.getName());

    private ArrayList<String> usernames = new ArrayList<>();

    public Users() {
        initComponents();
        setLocationRelativeTo(null);
        loadUsers();
        setupButtons();
        
        btnUser1.setPreferredSize(new java.awt.Dimension(200, 40));
        btnUser2.setPreferredSize(new java.awt.Dimension(200, 40));
        btnUser3.setPreferredSize(new java.awt.Dimension(200, 40));
        btnOther.setPreferredSize(new java.awt.Dimension(200, 40));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUser1 = new javax.swing.JButton();
        btnUser2 = new javax.swing.JButton();
        btnUser3 = new javax.swing.JButton();
        btnOther = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUser1.setText("-------");
        btnUser1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUser1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 97, -1, -1));

        btnUser2.setText("-------");
        btnUser2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(btnUser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 97, -1, -1));

        btnUser3.setText("-------");
        btnUser3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(btnUser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 169, -1, -1));

        btnOther.setText("-------");
        btnOther.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(btnOther, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 169, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/securitysystem/stefan-stefancik--g7axSVst6Y-unsplash.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUser1ActionPerformed

    
    private void loadUsers() {
        try (Connection conn = DBConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement("SELECT username FROM users ORDER BY id ASC");
             ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                usernames.add(rs.getString("username"));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading users: " + e.getMessage());
        }
    }

    private void setupButtons() {
        JButton[] userButtons = {btnUser1, btnUser2, btnUser3};
        for (int i = 0; i < 3; i++) {
            if (i < usernames.size()) {
                String username = usernames.get(i);
                userButtons[i].setText(username);
                userButtons[i].addActionListener(e -> openLogin(username));
            } else {
                userButtons[i].setVisible(false);
            }
        }

        // If there are more than 3 users, show the "Other" button
        if (usernames.size() > 3) {
            btnOther.setText("Other User");
            btnOther.addActionListener(e -> {
                new Login().setVisible(true); // opens login screen directly
                dispose();
            });
        } else {
            btnOther.setVisible(false);
        }

    }
    
    private void openLogin(String username) {
        new Login(username).setVisible(true);
        dispose();
    }
     
    
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Users().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOther;
    private javax.swing.JButton btnUser1;
    private javax.swing.JButton btnUser2;
    private javax.swing.JButton btnUser3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
