/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package securitysystem;

import java.awt.event.*;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.*;
/**
 *
 * @author Julianna Boado
 */
public class Users extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Users.class.getName());

    private ArrayList<String> usernames = new ArrayList<>();

    public Users() {
        initComponents();
        setLocationRelativeTo(null);
        loadUsers();
        setupButtons();
        
        btnUser1.setPreferredSize(new java.awt.Dimension(200, 40));
        btnUser2.setPreferredSize(new java.awt.Dimension(200, 40));
        btnUser3.setPreferredSize(new java.awt.Dimension(200, 40));
        btnOther.setPreferredSize(new java.awt.Dimension(200, 40));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUser1 = new javax.swing.JButton();
        btnUser2 = new javax.swing.JButton();
        btnUser3 = new javax.swing.JButton();
        btnOther = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnUser1.setText("-------");
        btnUser1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUser1ActionPerformed(evt);
            }
        });

        btnUser2.setText("-------");
        btnUser2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnUser3.setText("-------");
        btnUser3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnOther.setText("-------");
        btnOther.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnOther)
                    .addComponent(btnUser3)
                    .addComponent(btnUser2)
                    .addComponent(btnUser1))
                .addGap(236, 236, 236))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnUser1)
                .addGap(29, 29, 29)
                .addComponent(btnUser2)
                .addGap(20, 20, 20)
                .addComponent(btnUser3)
                .addGap(18, 18, 18)
                .addComponent(btnOther)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUser1ActionPerformed

    
    private void loadUsers() {
        try (Connection conn = DBConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement("SELECT username FROM users ORDER BY id ASC");
             ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                usernames.add(rs.getString("username"));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading users: " + e.getMessage());
        }
    }

    private void setupButtons() {
        JButton[] userButtons = {btnUser1, btnUser2, btnUser3};
        for (int i = 0; i < 3; i++) {
            if (i < usernames.size()) {
                String username = usernames.get(i);
                userButtons[i].setText(username);
                userButtons[i].addActionListener(e -> openLogin(username));
            } else {
                userButtons[i].setVisible(false);
            }
        }

        // If there are more than 3 users, show the "Other" button
        if (usernames.size() > 3) {
            btnOther.setText("Other User");
            btnOther.addActionListener(e -> {
                new Login().setVisible(true); // opens login screen directly
                dispose();
            });
        } else {
            btnOther.setVisible(false);
        }

    }
    
    private void openLogin(String username) {
        new Login(username).setVisible(true);
        dispose();
    }
     
    
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Users().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOther;
    private javax.swing.JButton btnUser1;
    private javax.swing.JButton btnUser2;
    private javax.swing.JButton btnUser3;
    // End of variables declaration//GEN-END:variables
}
